apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud-deployment
  labels:
    app: gcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcloud
  template:
    metadata:
      labels:
        app: gcloud
    spec:
      containers:
      - name: gcloud
        image: pcarrascog/testgcp
        command:
        - cat
        tty: true
       

